import { Inter } from 'next/font/google'
import './globals.css'
import UserProvider from "@/app/context/userProvider";
import 'primereact/resources/themes/lara-light-indigo/theme.css';  //theme
import 'primereact/resources/primereact.min.css';                  //core css
import 'primeicons/primeicons.css';
import Navbar from "@/app/components/Navbar/Navbar";                                //icons


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <UserProvider>
          <Navbar/>
        {children}
      </UserProvider>
      </body>
    </html>
  )
}
